name: serach-for-military-type-front

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../:/workspace:cached
      - node_modules:/workspace/node_modules
    tty: true

volumes:
  node_modules:
